specs: Readability improvements to rollup-node
ethereum-optimism/optimistic-specs pull request #330
Opened 2022-04-07 03:26 UTC by maurelian

Mostly minor edits that I think improve the flow.

2022-04-07 12:18 UTC, norswap commented on specs/deposits.md
> -## User-Deposited Transactions
Yup! This is precisely defined in the glossary!
https://github.com/ethereum-optimism/optimistic-specs/blob/90e3620c126148c5c0f7023788c5d00d4025cbeb/specs/glossary.md#deposited-transaction

2022-04-07 12:25 UTC, norswap commented on specs/rollup-node.md
> +  - `random` (the output of the [`RANDOM` opcode][random])
The reason these were not in code case was that in my mind code case refers to "defined" terms.

They could be terms defined in the spec to be referred to later, or definitions in particular structures / code files.

It's not quite clear to me that this refers to a specific definition? If that's the case (e.g. the geth block structure) I think this is fine but we should link/mention the source of these definition.

2022-04-07 12:28 UTC, norswap commented on specs/rollup-node.md
> +  used to augmented the [deposited transactions][g-deposited] derived from them).
That's incorrect. The block height / transaction index here are from the L2 transaction index.

Agree the comment was confusing, I don't think we need to mention these values here at all.

2022-04-07 12:36 UTC, norswap commented on specs/rollup-node.md
> +    block.
Also change `block_time` to `l2_block_time` to match the usage in the next bullets.

Maybe move up the `l2_block_time` definition from below, though that's not super important, it should be pretty intuitive what the block time is.

2022-04-07 12:39 UTC, norswap commented on specs/rollup-node.md
> +  - The batch is the first batch with `batch.timestamp` in this sequencing window, i.e. one batch per L2 block number.
s/one batch per L2 block number/only one batch per L2 block will be considered, and subsequent batches for the same L2 block will be ignored./

2022-04-07 12:40 UTC, norswap commented on specs/rollup-node.md
> +  - The batch only contains sequenced transactions, i.e. it must NOT contain any Deposit-type transactions.
Add a link for "Deposit-type transactions".

2022-04-07 12:40 UTC, norswap commented on specs/rollup-node.md
> +The [deposited][g-deposited] transactions are all put in the first of the derived `PayloadAttributes`,
Same comment as above, keep user-deposited. The capital letter can go.

2022-04-07 12:44 UTC, norswap commented on specs/rollup-node.md
> +- Log entries emitted by the [Deposit Feed][[g-deposit-contract] contract, with the `TransactionDeposited` signature.
Extraneous `[`

2022-04-07 12:51 UTC, norswap requested changes
Ended up doing my review as loose comments.

Requested changes:
- revert to using "user-deposited" transactions
- clarify the glossary for bundle + batch
- open an issue that is "audit-critical" that we need to make sure the usage of "bundle" and "batch" is clear and consistent across the repo
- (bunch of small stuff)

2022-04-13 12:16 UTC, norswap commented on specs/glossary.md
> +## Sequencer bundle
> Sequencer batch is still defined above on line 178.

Yes, but could we state explicitly say that the transaction in a batch are meant to be part of a single L2 block? It's *sort of* implied by the fact that the transactions are tagged with a L2 timestamp, but the implication is easy to miss.

> I came across this term in [rollup-node.md](https://github.com/ethereum-optimism/optimistic-specs/blob/84176052f2049ac9013c133658371504b8c3a3c7/specs/rollup-node.md#L127) and thought it should be listed here.

Yeah, this escaped my scrutiny. Still a valid concern though. Feel free to merge as-is if you feel this is out of scope, but could you then please open an issue to track this and assign it to me?

2022-04-13 12:20 UTC, norswap commented on specs/rollup-node.md
> +  used to augmented the [deposited transactions][g-deposited] derived from them).
What do we think about removing this? Imho this really doesn't belong here?

2022-04-13 12:25 UTC, norswap approved these changes
Approving, but please see the above unresolved issues:
- capitalization
- removing the mention of "augmented with fields" which is just awkward at this place in the spec and is also specified elsewehre
- better definining bundles vs batches (or add an issue to improve this later)

2022-05-23 21:19 UTC, closed without merging

2022-05-23 21:21 UTC, maurelian commented
Closed because this is super old, and not that important.